/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.b0n541.pmcts;

import org.b0n541.pmcts.game.tictactoe.TicTacToe;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class App {

    private static final Logger LOG = LoggerFactory.getLogger(App.class);

    public static void main(final String[] args) {
        TicTacToe.playGame();
    }
}
