/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.b0n541.pmcts;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class App {

    private static final Logger LOG = LoggerFactory.getLogger(App.class);

    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        LOG.info(new App().getGreeting());
    }
}
